In [2]:
import pandas as pd
import pandas.io.sql as sqlio

In [3]:
pip install pandasql

Requirement already satisfied: pandasql in ./venv/lib/python3.9/site-packages (0.7.3)
Requirement already satisfied: pandas in ./venv/lib/python3.9/site-packages (from pandasql) (2.1.1)
Requirement already satisfied: sqlalchemy in ./venv/lib/python3.9/site-packages (from pandasql) (2.0.21)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from pandasql) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv/lib/python3.9/site-packages (from sqlalchemy->pandasql) (4.8.0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
from pandasql import sqldf

In [5]:
df_irr = pd.read_csv('Hackathon Data.csv')

/var/folders/hk/mycg00qn1bsb682mrds79j5h0000gn/T/ipykernel_59920/3764511131.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_irr = pd.read_csv('Hackathon Data.csv')

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
df_irr.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI',
       'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI',
       'Fill Flag', 'GHI', 'Relative Humidity', 'Solar Zenith Angle',
       'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction',
       'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)',
       'Global Horizontal UV Irradiance (295-385nm)'],
      dtype='object')

In [8]:
df_irr.head()

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
0,2011,5,14,0,0,11.4,0,0,0,8,10.1,0,0,0,0,91.68,119.80,0.16,984,2.7,347,4.9,0.0,0.0
1,2011,5,14,0,30,11.3,0,0,0,4,10.1,0,0,0,0,92.29,119.46,0.16,984,2.6,349,4.7,0.0,0.0
2,2011,5,14,1,0,11.2,0,0,0,4,10.0,0,0,0,0,92.03,118.34,0.16,984,2.6,350,4.6,0.0,0.0
3,2011,5,14,1,30,11.0,0,0,0,4,10.0,0,0,0,0,93.25,116.47,0.16,984,2.6,350,4.5,0.0,0.0
4,2011,5,14,2,0,10.9,0,0,0,7,9.7,0,0,0,0,92.48,113.93,0.16,984,2.6,350,4.4,0.0,0.0

In [9]:
df_irr.shape

(186480, 24)

In [10]:
df_energy = pd.read_csv('Energy data.csv')

In [11]:
df_energy.head()

              Timestamp        Value
0  2011-05-14T00:00:00Z  0.072630554
1  2011-05-14T00:30:00Z            0
2  2011-05-14T01:00:00Z            0
3  2011-05-14T01:30:00Z            0
4  2011-05-14T02:00:00Z            0

In [12]:
df_energy.dtypes

Timestamp    object
Value        object
dtype: object

In [13]:
df_energy['Timestamp'] = pd.to_datetime(df_energy['Timestamp'])

# Convert 'FloatColumn' from float64 to int
df_energy['Value'] = pd.to_numeric(df_energy['Value'], errors='coerce').astype(float)

In [14]:
df_energy.head()

                  Timestamp     Value
0 2011-05-14 00:00:00+00:00  0.072631
1 2011-05-14 00:30:00+00:00  0.000000
2 2011-05-14 01:00:00+00:00  0.000000
3 2011-05-14 01:30:00+00:00  0.000000
4 2011-05-14 02:00:00+00:00  0.000000

In [15]:
import pytz
cst_timezone = pytz.timezone('US/Central')  # US/Central is the timezone code for CST
utc_timezone = pytz.timezone('UTC')
df_energy['Timestamp_CST'] = df_energy['Timestamp'].dt.tz_convert('US/Central')
#df_energy['Timestamp_CST'] = pd.to_datetime(df_energy['Timestamp']).dt.tz_localize(utc_timezone).dt.tz_convert(cst_timezone)
# Display the DataFrame with the converted timestamp column
print(df_energy)

                       Timestamp     Value             Timestamp_CST
0      2011-05-14 00:00:00+00:00  0.072631 2011-05-13 19:00:00-05:00
1      2011-05-14 00:30:00+00:00  0.000000 2011-05-13 19:30:00-05:00
2      2011-05-14 01:00:00+00:00  0.000000 2011-05-13 20:00:00-05:00
3      2011-05-14 01:30:00+00:00  0.000000 2011-05-13 20:30:00-05:00
4      2011-05-14 02:00:00+00:00  0.000000 2011-05-13 21:00:00-05:00
...                          ...       ...                       ...
186475 2021-12-31 21:30:00+00:00  0.000000 2021-12-31 15:30:00-06:00
186476 2021-12-31 22:00:00+00:00  0.054113 2021-12-31 16:00:00-06:00
186477 2021-12-31 22:30:00+00:00  0.162339 2021-12-31 16:30:00-06:00
186478 2021-12-31 23:00:00+00:00  0.162339 2021-12-31 17:00:00-06:00
186479 2021-12-31 23:30:00+00:00  0.162340 2021-12-31 17:30:00-06:00

[186480 rows x 3 columns]

In [16]:
df_energy = df_energy.iloc[10:,:].reset_index(drop=True)

In [17]:
df_energy = df_energy.drop(columns = ['Timestamp'])

In [18]:
df_energy

           Value             Timestamp_CST
0       0.000000 2011-05-14 00:00:00-05:00
1       0.000000 2011-05-14 00:30:00-05:00
2       0.000000 2011-05-14 01:00:00-05:00
3       0.000000 2011-05-14 01:30:00-05:00
4       0.000000 2011-05-14 02:00:00-05:00
...          ...                       ...
186465  0.000000 2021-12-31 15:30:00-06:00
186466  0.054113 2021-12-31 16:00:00-06:00
186467  0.162339 2021-12-31 16:30:00-06:00
186468  0.162339 2021-12-31 17:00:00-06:00
186469  0.162340 2021-12-31 17:30:00-06:00

[186470 rows x 2 columns]

In [19]:
df_energy[df_energy['Value']>38]

               Value             Timestamp_CST
49383   5.510000e+29 2014-03-07 18:30:00-06:00
49384   5.510000e+29 2014-03-07 19:00:00-06:00
49385   5.510000e+29 2014-03-07 19:30:00-06:00
49386   5.510000e+29 2014-03-07 20:00:00-06:00
49387   5.510000e+29 2014-03-07 20:30:00-06:00
...              ...                       ...
186446  9.160280e+01 2021-12-31 06:00:00-06:00
186447  9.160280e+01 2021-12-31 06:30:00-06:00
186448  9.160280e+01 2021-12-31 07:00:00-06:00
186449  9.160280e+01 2021-12-31 07:30:00-06:00
186450  9.153516e+01 2021-12-31 08:00:00-06:00

[33940 rows x 2 columns]

In [20]:
df_irr['Energy'] = df_energy['Value']

In [21]:
df_final = df_irr

In [22]:
#df_final = df_final.iloc[:186470,:].reset_index(drop=True)

In [23]:
df_final = df_final.iloc[:-10,:].reset_index(drop=True)

In [24]:
print(df_final.describe())

                Year          Month            Day           Hour  \
count  186470.000000  186470.000000  186470.000000  186470.000000
mean     2016.170912       6.651708      15.765206      11.499491
std         3.075225       3.425930       8.800575       6.922033
min      2011.000000       1.000000       1.000000       0.000000
25%      2014.000000       4.000000       8.000000       5.000000
50%      2016.000000       7.000000      16.000000      11.000000
75%      2019.000000      10.000000      23.000000      17.000000
max      2021.000000      12.000000      31.000000      23.000000

             Minute    Temperature   Clearsky DHI   Clearsky DNI  \
count  186470.00000  186470.000000  186470.000000  186470.000000
mean       15.00000      10.444590      44.802783     346.067689
std        15.00004      12.315954      54.985616     380.661624
min         0.00000     -35.400000       0.000000       0.000000
25%         0.00000       0.500000       0.000000       0.000000
50%        15.00000      11.200000       7.000000      35.000000
75%        30.00000      20.800000      85.000000     763.000000
max        30.00000      43.000000     496.000000    1062.000000

        Clearsky GHI      Dew Point            DHI            DNI  \
count  186470.000000  186470.000000  186470.000000  186470.000000
mean      232.654186       5.894934      62.326240     200.250775
std       304.462204      11.612318      93.979731     315.998478
min         0.000000     -39.800000       0.000000       0.000000
25%         0.000000      -2.600000       0.000000       0.000000
50%         8.000000       6.400000       4.000000       0.000000
75%       455.000000      15.900000      95.000000     348.750000
max      1028.000000      28.600000     478.000000    1062.000000

           Fill Flag            GHI  Relative Humidity  Solar Zenith Angle  \
count  186470.000000  186470.000000      186470.000000       186470.000000
mean        3.118732     172.018990          76.227026           89.548525
std        14.458874     256.897243          18.220902           35.322048
min         0.000000       0.000000          16.250000           18.280000
25%         0.000000       0.000000          64.090000           62.330000
50%         0.000000       4.000000          79.720000           89.225000
75%         0.000000     285.000000          91.230000          116.740000
max       100.000000    1028.000000         100.000000          161.770000

       Surface Albedo       Pressure  Precipitable Water  Wind Direction  \
count   186470.000000  186470.000000       186470.000000   186470.000000
mean         0.249541     990.569561            1.970927      195.973545
std          0.216328       7.152779            1.314691       99.520186
min          0.130000     958.000000            0.100000        0.000000
25%          0.150000     986.000000            0.900000      123.000000
50%          0.160000     990.000000            1.600000      195.000000
75%          0.170000     995.000000            2.900000      287.000000
max          0.800000    1020.000000            6.900000      360.000000

          Wind Speed  Global Horizontal UV Irradiance (280-400nm)  \
count  186470.000000                                186470.000000
mean        3.164014                                     9.645770
std         1.770719                                    15.282771
min         0.200000                                     0.000000
25%         1.800000                                     0.000000
50%         2.900000                                     0.000000
75%         4.200000                                    15.339550
max        13.800000                                    63.074900

       Global Horizontal UV Irradiance (295-385nm)        Energy
count                                186470.000000  1.860930e+05
mean                                      7.553785  7.967870e+28
std                                      12.003694  2.370749e+29
min                                       0.000000  0.000000e+00
25%                                       0.000000  0.000000e+00
50%                                       0.000000  3.300000e+00
75%                                      11.946100  2.196350e+01
max                                      49.666500  6.020000e+30

In [25]:
df_final = df_final[df_final['Energy']<=38]

In [26]:
df_final

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy
0,2011,5,14,0,0,11.4,0,0,0,8,10.1,0,0,0,0,91.68,119.80,0.16,984,2.7,347,4.9,0.0,0.0,0.000000
1,2011,5,14,0,30,11.3,0,0,0,4,10.1,0,0,0,0,92.29,119.46,0.16,984,2.6,349,4.7,0.0,0.0,0.000000
2,2011,5,14,1,0,11.2,0,0,0,4,10.0,0,0,0,0,92.03,118.34,0.16,984,2.6,350,4.6,0.0,0.0,0.000000
3,2011,5,14,1,30,11.0,0,0,0,4,10.0,0,0,0,0,93.25,116.47,0.16,984,2.6,350,4.5,0.0,0.0,0.000000
4,2011,5,14,2,0,10.9,0,0,0,7,9.7,0,0,0,0,92.48,113.93,0.16,984,2.6,350,4.4,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186465,2021,12,31,16,30,-0.2,18,107,22,7,-0.5,9,0,86,9,97.77,88.02,0.74,979,0.9,9,4.6,0.0,0.0,0.000000
186466,2021,12,31,17,0,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,93.14,0.74,979,0.9,7,4.7,0.0,0.0,0.054113
186467,2021,12,31,17,30,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,98.17,0.74,979,0.9,7,4.7,0.0,0.0,0.162339
186468,2021,12,31,18,0,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,103.35,0.80,999,0.4,84,1.7,0.0,0.0,0.162339
186469,2021,12,31,18,30,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,108.71,0.80,999,0.4,89,1.9,0.0,0.0,0.162340

In [ ]:
print(df_final.describe())

In [27]:
df_final = df_final[df_final['Energy']<=38]

In [ ]:
df_final

In [28]:
df_final['conversion_efficiency'] = df_final['Energy']*1000/(df_final['GHI']*24.8171891)

In [35]:
df_final

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency
0,2011,5,14,0,0,11.4,0,0,0,8,10.1,0,0,0,0,91.68,119.80,0.16,984,2.7,347,4.9,0.0,0.0,0.000000,NaN
1,2011,5,14,0,30,11.3,0,0,0,4,10.1,0,0,0,0,92.29,119.46,0.16,984,2.6,349,4.7,0.0,0.0,0.000000,NaN
2,2011,5,14,1,0,11.2,0,0,0,4,10.0,0,0,0,0,92.03,118.34,0.16,984,2.6,350,4.6,0.0,0.0,0.000000,NaN
3,2011,5,14,1,30,11.0,0,0,0,4,10.0,0,0,0,0,93.25,116.47,0.16,984,2.6,350,4.5,0.0,0.0,0.000000,NaN
4,2011,5,14,2,0,10.9,0,0,0,7,9.7,0,0,0,0,92.48,113.93,0.16,984,2.6,350,4.4,0.0,0.0,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186465,2021,12,31,16,30,-0.2,18,107,22,7,-0.5,9,0,86,9,97.77,88.02,0.74,979,0.9,9,4.6,0.0,0.0,0.000000,0.0
186466,2021,12,31,17,0,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,93.14,0.74,979,0.9,7,4.7,0.0,0.0,0.054113,inf
186467,2021,12,31,17,30,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,98.17,0.74,979,0.9,7,4.7,0.0,0.0,0.162339,inf
186468,2021,12,31,18,0,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,103.35,0.80,999,0.4,84,1.7,0.0,0.0,0.162339,inf
186469,2021,12,31,18,30,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,108.71,0.80,999,0.4,89,1.9,0.0,0.0,0.162340,inf

In [ ]:
(df_final['Energy'].sum())*1000/(df_final['GHI'].sum()*24.8171891)

In [38]:
df_final_bb_cons = df_final[df_final['conversion_efficiency']<=0.09]

In [39]:
df_final_bb_cons.to_csv('BusBarn.csv')

In [31]:
df_final_bb_cons['conversion_efficiency'].describe()

count    12991.000000
mean         0.015129
std          0.024763
min          0.000000
25%          0.000000
50%          0.000000
75%          0.022676
max          0.089851
Name: conversion_efficiency, dtype: float64

In [32]:
df_final_bb_cons

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency
10,2011,5,14,5,0,9.7,11,40,12,8,8.3,3,0,7,3,91.24,88.45,0.16,984,2.7,350,4.7,0.0000,0.0000,0.0,0.0
11,2011,5,14,5,30,9.7,42,214,66,7,8.4,12,0,7,12,91.33,83.45,0.16,985,2.7,351,4.8,0.0000,0.0000,0.0,0.0
12,2011,5,14,6,0,9.6,68,370,144,7,7.9,10,0,0,10,89.29,78.14,0.16,985,2.7,351,4.8,0.4783,0.3654,0.0,0.0
13,2011,5,14,6,30,9.8,88,487,233,7,7.9,6,0,0,6,88.11,72.68,0.16,985,2.7,353,4.8,0.2997,0.2312,0.0,0.0
14,2011,5,14,7,0,9.9,107,563,326,7,7.7,83,0,0,83,86.13,67.13,0.16,985,2.7,354,4.8,4.3546,3.3830,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186461,2021,12,31,14,30,1.1,88,662,289,6,0.4,96,21,0,102,95.28,72.36,0.74,977,1.0,46,2.8,5.1099,3.9442,0.0,0.0
186462,2021,12,31,15,0,0.9,79,579,222,6,0.1,72,10,0,74,94.72,75.71,0.74,977,1.0,28,3.1,3.5968,2.7606,0.0,0.0
186463,2021,12,31,15,30,0.5,64,476,151,6,0.2,43,1,14,43,97.58,79.51,0.74,978,1.0,19,3.8,2.0495,1.5627,0.0,0.0
186464,2021,12,31,16,0,0.2,45,323,81,6,-0.5,26,0,100,26,94.88,83.66,0.74,978,1.0,11,4.4,0.0000,0.0000,0.0,0.0
186465,2021,12,31,16,30,-0.2,18,107,22,7,-0.5,9,0,86,9,97.77,88.02,0.74,979,0.9,9,4.6,0.0000,0.0000,0.0,0.0

In [ ]:
(df_final_bb_cons['Energy'].sum())*1000*100/(df_final_bb_cons['GHI'].sum()*24.8171891)

In [ ]:
result_year = df_final_bb_cons.groupby('Year')['Energy'].sum()*1000*100/(df_final_bb_cons.groupby('Year')['GHI'].sum()*24.8171891)

print(result_year)

In [ ]:
result_month = df_final_bb_cons.groupby('Month')['Energy'].sum()*1000*100/(df_final_bb_cons.groupby('Month')['GHI'].sum()*24.8171891)

print(result_month)

In [ ]:
columns_to_add = ['column1', 'column2', 'column3']  # Replace with actual column names
columns_to_replace = ['Year', 'Month','Day','Hour','Minute']

In [82]:
query = ''' WITH CTE as (SELECT * FROM df_final_bb_cons)
SELECT *, sum(GHI) over(partition by Minute) as Hourly_GHI, 
sum(Energy) over(partition by Minute) as Hourly_Energy FROM CTE GROUP by Year, Month, Day, Hour, Minute, Temperature, "Clearsky DHI",
       "Clearsky DNI", "Clearsky GHI", "Cloud Type", "Dew Point", DHI, DNI,
       "Fill Flag", GHI, "Relative Humidity", "Solar Zenith Angle",
       "Surface Albedo", Pressure, "Precipitable Water", "Wind Direction",
       "Wind Speed", "Global Horizontal UV Irradiance (280-400nm)",
       "Global Horizontal UV Irradiance (295-385nm)"
'''

In [83]:
query_out = sqldf(query)

In [86]:
query_out.head(50)

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency,Hourly_GHI,Hourly_Energy
0,2011,5,14,5,0,9.7,11,40,12,8,8.3,3,0,7,3,91.24,88.45,0.16,984,2.7,350,4.7,0.0000,0.0000,0.000000,0.000000,895391,472.334079
1,2011,5,14,6,0,9.6,68,370,144,7,7.9,10,0,0,10,89.29,78.14,0.16,985,2.7,351,4.8,0.4783,0.3654,0.000000,0.000000,895391,472.334079
2,2011,5,14,7,0,9.9,107,563,326,7,7.7,83,0,0,83,86.13,67.13,0.16,985,2.7,354,4.8,4.3546,3.3830,0.000000,0.000000,895391,472.334079
3,2011,5,14,8,0,10.4,138,666,511,7,7.8,187,12,0,194,83.81,55.95,0.16,985,2.7,352,4.6,10.9291,8.5528,0.071506,0.014852,895391,472.334079
4,2011,5,14,9,0,10.8,161,732,679,7,7.9,129,0,0,129,82.42,44.95,0.16,985,2.6,347,4.8,7.5769,5.9491,0.150646,0.047056,895391,472.334079
5,2011,5,15,5,0,7.5,13,62,15,4,6.2,3,0,7,3,91.31,88.30,0.16,987,2.3,10,3.9,0.0000,0.0000,0.000000,0.000000,895391,472.334079
6,2011,5,15,6,0,7.9,61,439,153,4,6.0,5,0,0,5,87.96,77.98,0.16,987,2.2,17,4.4,0.2393,0.1829,0.000000,0.000000,895391,472.334079
7,2011,5,16,5,0,3.0,14,168,20,0,1.1,14,168,0,20,87.10,88.14,0.16,994,0.6,7,3.1,0.0000,0.0000,0.000000,0.000000,895391,472.334079
8,2011,5,16,6,0,5.1,48,614,177,0,1.5,48,614,0,177,77.40,77.83,0.16,994,0.6,6,3.7,8.4778,6.4814,0.013893,0.003163,895391,472.334079
9,2011,5,17,5,0,3.2,15,143,20,0,1.1,15,143,0,20,86.26,88.00,0.17,993,0.6,33,1.2,0.0000,0.0000,0.000000,0.000000,895391,472.334079
10,2011,5,17,6,0,6.2,51,595,178,0,1.1,51,595,0,178,69.66,77.69,0.17,993,0.5,32,2.7,8.5320,6.5245,0.017472,0.003955,895391,472.334079
11,2011,5,18,5,0,6.5,15,161,21,0,4.2,15,161,0,21,85.53,87.87,0.17,987,1.2,19,1.3,0.0000,0.0000,0.000000,0.000000,895391,472.334079
12,2011,5,18,6,0,9.7,48,578,173,0,4.7,48,578,0,173,70.98,77.56,0.17,987,1.3,15,2.5,8.2984,6.3474,0.012133,0.002826,895391,472.334079
13,2011,5,19,5,0,10.5,16,68,19,4,10.4,5,0,7,5,99.09,87.74,0.17,990,2.2,98,2.4,0.0000,0.0000,0.000000,0.000000,895391,472.334079
14,2011,5,19,6,0,12.1,70,409,159,7,10.8,72,1,0,73,92.01,77.42,0.17,989,2.1,90,3.2,3.5045,2.6813,0.033784,0.018648,895391,472.334079
15,2011,5,20,5,0,14.2,14,39,16,7,13.6,5,0,7,5,96.09,87.61,0.17,991,3.6,131,3.3,0.0000,0.0000,0.000000,0.000000,895391,472.334079
16,2011,5,20,6,0,15.4,83,291,147,7,14.0,32,0,0,32,91.49,77.30,0.17,991,3.6,126,3.9,1.5374,1.1765,0.000000,0.000000,895391,472.334079
17,2011,5,20,7,0,17.5,130,486,325,7,14.8,161,78,0,192,84.03,66.33,0.17,990,3.4,125,4.5,10.1377,7.8818,0.322677,0.067720,895391,472.334079
18,2011,5,21,5,0,17.7,12,26,13,4,17.4,5,0,7,5,98.36,87.49,0.17,983,3.7,157,2.8,0.0000,0.0000,0.000000,0.000000,895391,472.334079
19,2011,5,21,6,0,18.6,92,225,142,7,18.1,3,0,0,3,96.73,77.18,0.17,983,3.7,161,3.2,0.1442,0.1104,0.000000,0.000000,895391,472.334079
20,2011,5,22,5,0,17.1,17,113,22,0,16.9,17,113,0,22,98.79,87.37,0.17,980,2.7,173,3.9,0.0000,0.0000,0.000000,0.000000,895391,472.334079
21,2011,5,22,6,0,18.4,59,482,167,0,17.7,59,482,0,167,95.62,77.06,0.17,980,2.6,167,4.4,8.0354,6.1519,0.013675,0.003300,895391,472.334079
22,2011,5,22,16,0,26.2,147,651,531,9,20.8,40,0,0,40,72.16,53.84,0.17,975,3.7,210,5.1,2.2754,1.7822,0.028697,0.028909,895391,472.334079
23,2011,5,23,5,0,14.3,17,169,25,4,13.4,5,0,7,5,94.49,87.25,0.17,978,2.9,254,3.1,0.0000,0.0000,0.000000,0.000000,895391,472.334079
24,2011,5,23,6,0,15.9,54,518,171,3,14.0,61,0,7,61,88.49,76.95,0.17,978,2.8,256,3.3,2.9373,2.2492,0.000000,0.000000,895391,472.334079
25,2011,5,24,5,0,16.1,17,188,27,0,15.1,17,188,0,27,93.97,87.14,0.17,983,2.7,331,0.8,0.0000,0.0000,0.000000,0.000000,895391,472.334079
26,2011,5,24,6,0,18.5,52,540,175,0,16.1,52,540,0,175,85.91,76.85,0.17,983,2.7,27,1.5,8.4323,6.4582,0.034385,0.007917,895391,472.334079
27,2011,5,25,5,0,11.9,17,32,19,6,11.1,5,0,7,5,94.54,87.03,0.17,977,3.8,80,6.4,0.0000,0.0000,0.000000,0.000000,895391,472.334079
28,2011,5,25,6,0,12.7,92,254,150,6,11.9,16,0,0,16,94.79,76.75,0.17,975,4.0,78,7.3,0.7715,0.5910,0.000000,0.000000,895391,472.334079
29,2011,5,25,7,0,13.3,111,548,336,6,12.5,56,0,0,56,94.82,65.81,0.17,973,4.4,81,7.0,2.9688,2.3092,0.000000,0.000000,895391,472.334079
30,2011,5,26,5,0,8.3,21,123,28,7,5.5,10,0,7,10,82.53,86.93,0.17,985,2.2,14,5.3,0.0000,0.0000,0.000000,0.000000,895391,472.334079
31,2011,5,26,6,0,8.5,63,500,178,6,5.1,85,74,0,102,79.45,76.65,0.17,986,2.0,12,5.2,4.9218,3.7710,0.000758,0.000299,895391,472.334079
32,2011,5,27,5,0,6.8,22,150,30,7,4.4,19,19,7,20,84.90,86.83,0.18,991,1.1,97,2.7,0.0000,0.0000,0.000000,0.000000,895391,472.334079
33,2011,5,27,6,0,7.7,63,527,185,7,4.3,83,172,0,123,79.20,76.56,0.18,991,1.1,97,2.5,5.9390,4.5511,0.077612,0.025426,895391,472.334079
34,2011,5,28,5,0,11.7,22,115,29,4,11.6,9,0,7,9,99.67,86.74,0.18,983,2.3,219,1.9,0.0000,0.0000,0.000000,0.000000,895391,472.334079
35,2011,5,28,6,0,13.6,70,450,175,4,12.6,75,0,0,75,93.43,76.48,0.18,983,2.3,221,2.5,3.6235,2.7771,0.006837,0.003673,895391,472.334079
36,2011,5,29,5,0,12.5,21,88,27,7,12.4,16,0,7,16,99.29,86.66,0.18,983,3.8,59,2.3,0.0000,0.0000,0.000000,0.000000,895391,472.334079
37,2011,5,29,6,0,13.8,73,398,167,7,13.1,58,0,0,58,95.48,76.40,0.18,983,3.8,54,3.2,2.8038,2.1492,0.040019,0.027803,895391,472.334079
38,2011,5,29,9,0,19.6,170,697,678,9,16.4,49,0,0,49,81.89,43.23,0.18,983,4.2,74,5.2,2.8920,2.2715,0.000000,0.000000,895391,472.334079
39,2011,5,29,10,0,21.8,204,707,799,9,17.6,55,0,0,55,77.23,32.74,0.18,983,4.2,89,5.6,3.3206,2.6121,0.000000,0.000000,895391,472.334079
40,2011,5,29,11,0,23.6,223,719,879,9,19.4,73,0,0,73,77.12,24.06,0.18,982,4.1,107,5.2,4.4607,3.5116,0.000000,0.000000,895391,472.334079
41,2011,5,30,5,0,19.4,21,103,28,0,19.2,21,103,0,28,98.64,86.58,0.17,986,2.8,161,4.0,0.0000,0.0000,0.000000,0.000000,895391,472.334079
42,2011,5,30,6,0,20.5,75,399,169,0,19.9,75,399,0,169,96.16,76.33,0.17,986,2.8,159,4.4,8.1741,6.2665,0.144191,0.034379,895391,472.334079
43,2011,5,31,5,0,22.3,15,18,17,7,20.9,12,0,7,12,92.02,86.51,0.17,988,4.6,205,5.8,0.0000,0.0000,0.000000,0.000000,895391,472.334079
44,2011,5,31,6,0,22.6,105,175,147,7,21.2,71,0,0,71,91.56,76.26,0.17,989,4.7,204,5.5,3.4359,2.6344,0.009423,0.005348,895391,472.334079
45,2011,5,31,7,0,23.1,168,363,319,8,21.4,167,200,0,250,90.44,65.37,0.17,989,4.7,200,5.6,13.2979,10.3475,0.036923,0.005951,895391,472.334079
46,2011,5,31,9,0,25.1,194,650,669,6,21.7,114,0,0,114,81.25,43.10,0.17,989,4.3,214,6.8,6.7307,5.2866,0.000000,0.000000,895391,472.334079
47,2011,6,1,5,0,12.9,22,226,36,0,10.8,22,226,0,36,87.06,86.43,0.17,1000,1.5,331,1.2,0.0000,0.0000,0.000000,0.000000,895391,472.334079
48,2011,6,1,6,0,15.4,53,587,193,0,10.6,53,587,0,193,72.88,76.20,0.17,1000,1.6,318,1.8,9.3443,7.1653,0.084952,0.017736,895391,472.334079
49,2011,6,2,5,0,16.3,24,79,29,6,14.2,16,0,7,16,87.38,86.37,0.17,995,3.0,121,2.9,0.0000,0.0000,0.000000,0.000000,895391,472.334079

In [52]:
query_out['conversion_efficiency'] = query_out['Hourly_Energy']*1000/(query_out['Hourly_GHI']*24.8171891)

In [104]:
sorted_df_hourly = query_out.sort_values(by = 'Hour')

In [105]:
selected_columns_df = sorted_df_hourly[['Year','Month', 'Day','Hour','GHI','Energy','conversion_efficiency']]

# Specify the path where you want to save the CSV file

# Write the selected columns to the CSV file
selected_columns_df.to_csv('Hourly_eff.csv')

In [89]:
query_Daily = ''' WITH CTE as (SELECT * FROM df_final_bb_cons)
SELECT *, sum(GHI) over(partition by Hour) as Daily_GHI, 
sum(Energy) over(partition by Hour) as Daily_Energy FROM CTE GROUP by Year, Month, Day, Hour, Minute, Temperature, "Clearsky DHI",
       "Clearsky DNI", "Clearsky GHI", "Cloud Type", "Dew Point", DHI, DNI,
       "Fill Flag", GHI, "Relative Humidity", "Solar Zenith Angle",
       "Surface Albedo", Pressure, "Precipitable Water", "Wind Direction",
       "Wind Speed", "Global Horizontal UV Irradiance (280-400nm)",
       "Global Horizontal UV Irradiance (295-385nm)"
'''

In [90]:
Daily_df = sqldf(query_Daily)

In [95]:
Daily_df['conversion_efficiency'] = Daily_df['Daily_Energy']*1000/(Daily_df['Daily_GHI']*24.8171891)

In [98]:
sorted_daily_df= Daily_df.sort_values(by = 'Day')

In [102]:

# Create a new DataFrame with only the selected columns
selected_columns_df = sorted_daily_df[['Year','Month', 'Day','GHI','Energy','conversion_efficiency']]

# Specify the path where you want to save the CSV file

# Write the selected columns to the CSV file
selected_columns_df.to_csv('Daily_eff.csv')

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency,Daily_GHI,Daily_Energy
12986,2021,5,8,19,0,5.5,11,29,12,7,4.4,4,0,86,4,92.85,88.41,0.16,988,2.6,69,5.7,0.0,0.0,0.0000,0.008162,545,0.110393
12987,2021,6,20,19,0,25.1,41,171,60,9,23.7,17,0,100,17,92.00,83.56,0.16,974,4.8,217,2.9,0.0,0.0,0.0045,0.008162,545,0.110393
12988,2021,6,20,19,30,24.7,11,37,12,9,23.7,6,0,86,6,94.31,88.31,0.16,975,4.8,233,3.3,0.0,0.0,0.0000,0.008162,545,0.110393
12989,2021,7,9,19,0,21.6,41,116,54,6,20.1,15,0,100,15,91.00,83.77,0.16,989,4.6,108,3.5,0.0,0.0,0.0000,0.008162,545,0.110393
12990,2021,7,9,19,30,21.2,8,21,9,6,20.1,5,0,82,5,93.34,88.56,0.16,990,4.7,107,3.6,0.0,0.0,0.0000,0.008162,545,0.110393

In [ ]:
# Initialize a new DataFrame to store the results
new_df = pd.DataFrame()

# Iterate through rows in steps of 2
for i in range(0, len(df), 2):
    # Take two consecutive rows
    row1 = df.iloc[i]
    row2 = df.iloc[i+1]
    
    # Add specified columns and replace others with upper row
    result_row = row1.copy()
    result_row[columns_to_add] = (row1[columns_to_add] + row2[columns_to_add]) / 2
    result_row[columns_to_replace] = row1[columns_to_replace]
    
    # Append the result to the new DataFrame
    new_df = new_df.append(result_row, ignore_index=True)

# Print or save the new DataFrame
print(new_df)