In [2]:
import pandas as pd
import pandas.io.sql as sqlio

In [3]:
pip install pandasql

Requirement already satisfied: pandasql in ./venv/lib/python3.9/site-packages (0.7.3)
Requirement already satisfied: pandas in ./venv/lib/python3.9/site-packages (from pandasql) (2.1.1)
Requirement already satisfied: sqlalchemy in ./venv/lib/python3.9/site-packages (from pandasql) (2.0.21)
Requirement already satisfied: numpy in ./venv/lib/python3.9/site-packages (from pandasql) (1.26.0)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas->pandasql) (2023.3.post1)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv/lib/python3.9/site-packages (from sqlalchemy->pandasql) (4.8.0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
from pandasql import sqldf

In [5]:
df_irr = pd.read_csv('Hackathon Data.csv')

/var/folders/hk/mycg00qn1bsb682mrds79j5h0000gn/T/ipykernel_59934/3764511131.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_irr = pd.read_csv('Hackathon Data.csv')

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
df_irr.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Clearsky DHI',
       'Clearsky DNI', 'Clearsky GHI', 'Cloud Type', 'Dew Point', 'DHI', 'DNI',
       'Fill Flag', 'GHI', 'Relative Humidity', 'Solar Zenith Angle',
       'Surface Albedo', 'Pressure', 'Precipitable Water', 'Wind Direction',
       'Wind Speed', 'Global Horizontal UV Irradiance (280-400nm)',
       'Global Horizontal UV Irradiance (295-385nm)'],
      dtype='object')

In [8]:
df_irr.head()

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
0,2011,5,14,0,0,11.4,0,0,0,8,10.1,0,0,0,0,91.68,119.80,0.16,984,2.7,347,4.9,0.0,0.0
1,2011,5,14,0,30,11.3,0,0,0,4,10.1,0,0,0,0,92.29,119.46,0.16,984,2.6,349,4.7,0.0,0.0
2,2011,5,14,1,0,11.2,0,0,0,4,10.0,0,0,0,0,92.03,118.34,0.16,984,2.6,350,4.6,0.0,0.0
3,2011,5,14,1,30,11.0,0,0,0,4,10.0,0,0,0,0,93.25,116.47,0.16,984,2.6,350,4.5,0.0,0.0
4,2011,5,14,2,0,10.9,0,0,0,7,9.7,0,0,0,0,92.48,113.93,0.16,984,2.6,350,4.4,0.0,0.0

In [9]:
df_irr.shape

(186480, 24)

In [10]:
df_energy_ev = pd.read_csv('EV_FLowTag.csv')

In [11]:
df_energy_ev.head()

              Timestamp        Value
0  2011-06-02T00:00:00Z  5.173000336
1  2011-06-02T00:30:00Z  1.506789565
2  2011-06-02T01:00:00Z  0.708880424
3  2011-06-02T01:30:00Z            0
4  2011-06-02T02:00:00Z            0

In [12]:
df_energy_ev.dtypes

Timestamp    object
Value        object
dtype: object

In [13]:
df_energy_ev['Timestamp'] = pd.to_datetime(df_energy_ev['Timestamp'])

# Convert 'FloatColumn' from float64 to int
df_energy_ev['Value'] = pd.to_numeric(df_energy_ev['Value'], errors='coerce').astype(float)

In [14]:
df_energy_ev.head()

                  Timestamp    Value
0 2011-06-02 00:00:00+00:00  5.17300
1 2011-06-02 00:30:00+00:00  1.50679
2 2011-06-02 01:00:00+00:00  0.70888
3 2011-06-02 01:30:00+00:00  0.00000
4 2011-06-02 02:00:00+00:00  0.00000

In [15]:
import pytz
cst_timezone = pytz.timezone('US/Central')  # US/Central is the timezone code for CST
utc_timezone = pytz.timezone('UTC')
df_energy_ev['Timestamp_CST'] = df_energy_ev['Timestamp'].dt.tz_convert('US/Central')
#df_energy['Timestamp_CST'] = pd.to_datetime(df_energy['Timestamp']).dt.tz_localize(utc_timezone).dt.tz_convert(cst_timezone)
# Display the DataFrame with the converted timestamp column
print(df_energy_ev)

                       Timestamp      Value             Timestamp_CST
0      2011-06-02 00:00:00+00:00   5.173000 2011-06-01 19:00:00-05:00
1      2011-06-02 00:30:00+00:00   1.506790 2011-06-01 19:30:00-05:00
2      2011-06-02 01:00:00+00:00   0.708880 2011-06-01 20:00:00-05:00
3      2011-06-02 01:30:00+00:00   0.000000 2011-06-01 20:30:00-05:00
4      2011-06-02 02:00:00+00:00   0.000000 2011-06-01 21:00:00-05:00
...                          ...        ...                       ...
185659 2021-12-31 21:30:00+00:00   0.000000 2021-12-31 15:30:00-06:00
185660 2021-12-31 22:00:00+00:00   0.000000 2021-12-31 16:00:00-06:00
185661 2021-12-31 22:30:00+00:00  65.282661 2021-12-31 16:30:00-06:00
185662 2021-12-31 23:00:00+00:00   0.189396 2021-12-31 17:00:00-06:00
185663 2021-12-31 23:30:00+00:00   0.189396 2021-12-31 17:30:00-06:00

[185664 rows x 3 columns]

In [16]:
df_energy_ev = df_energy_ev.drop(columns = ['Timestamp'])

In [17]:
df_energy_ev = df_energy_ev.iloc[10:,:].reset_index()

In [18]:
df_energy_ev

         index      Value             Timestamp_CST
0           10   0.000000 2011-06-02 00:00:00-05:00
1           11   0.000000 2011-06-02 00:30:00-05:00
2           12   0.000000 2011-06-02 01:00:00-05:00
3           13   0.000000 2011-06-02 01:30:00-05:00
4           14   0.000000 2011-06-02 02:00:00-05:00
...        ...        ...                       ...
185649  185659   0.000000 2021-12-31 15:30:00-06:00
185650  185660   0.000000 2021-12-31 16:00:00-06:00
185651  185661  65.282661 2021-12-31 16:30:00-06:00
185652  185662   0.189396 2021-12-31 17:00:00-06:00
185653  185663   0.189396 2021-12-31 17:30:00-06:00

[185654 rows x 3 columns]

In [19]:
df_energy_ev[df_energy_ev['Value']>49.5]

         index         Value             Timestamp_CST
48471    48481  6.420000e+29 2014-03-07 18:30:00-06:00
48472    48482  6.420000e+29 2014-03-07 19:00:00-06:00
48473    48483  6.420000e+29 2014-03-07 19:30:00-06:00
48474    48484  6.420000e+29 2014-03-07 20:00:00-06:00
48475    48485  5.500000e+29 2014-03-07 20:30:00-06:00
...        ...           ...                       ...
182917  182927  3.364117e+02 2021-11-04 18:30:00-05:00
184884  184894  6.506193e+01 2021-12-15 17:00:00-06:00
185412  185422  1.148753e+02 2021-12-26 17:00:00-06:00
185603  185613  3.420407e+02 2021-12-30 16:30:00-06:00
185651  185661  6.528266e+01 2021-12-31 16:30:00-06:00

[26371 rows x 3 columns]

In [20]:
df_irr = df_irr.iloc[912:,:].reset_index()

In [21]:
df_irr = df_irr.iloc[:-10,:].reset_index()

In [22]:
df_irr

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm)
0,0,912,2011,6,2,0,0,17.0,0,0,0,7,13.9,0,0,0,0,82.08,116.20,0.17,994,2.3,115,1.5,0.0,0.0
1,1,913,2011,6,2,0,30,17.0,0,0,0,6,13.9,0,0,0,0,82.17,115.92,0.17,995,2.4,124,1.6,0.0,0.0
2,2,914,2011,6,2,1,0,17.0,0,0,0,7,14.0,0,0,0,0,82.39,114.90,0.17,995,2.4,134,1.7,0.0,0.0
3,3,915,2011,6,2,1,30,16.8,0,0,0,7,14.0,0,0,0,0,83.44,113.17,0.17,995,2.5,134,1.8,0.0,0.0
4,4,916,2011,6,2,2,0,16.7,0,0,0,7,13.9,0,0,0,0,83.30,110.78,0.17,994,2.5,134,1.8,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185553,185553,186465,2021,12,31,16,30,-0.2,18,107,22,7,-0.5,9,0,86,9,97.77,88.02,0.74,979,0.9,9,4.6,0.0,0.0
185554,185554,186466,2021,12,31,17,0,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,93.14,0.74,979,0.9,7,4.7,0.0,0.0
185555,185555,186467,2021,12,31,17,30,-0.6,0,0,0,7,-1.4,0,0,0,0,94.02,98.17,0.74,979,0.9,7,4.7,0.0,0.0
185556,185556,186468,2021,12,31,18,0,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,103.35,0.80,999,0.4,84,1.7,0.0,0.0
185557,185557,186469,2021,12,31,18,30,-10.7,0,0,0,7,-11.9,0,0,0,0,90.92,108.71,0.80,999,0.4,89,1.9,0.0,0.0

In [23]:
df_irr['Energy'] = df_energy_ev['Value']

In [24]:
df_final_ev = df_irr

In [25]:
#df_final = df_final.iloc[:186470,:].reset_index(drop=True)

In [26]:
df_final_ev = df_final_ev.iloc[:-10,:].reset_index(drop=True)

In [27]:
print(df_final_ev.describe())

             level_0          index           Year          Month  \
count  185548.000000  185548.000000  185548.000000  185548.000000
mean    92773.500000   93685.500000    2016.196068       6.659280
std     53563.238211   53563.238211       3.061158       3.432332
min         0.000000     912.000000    2011.000000       1.000000
25%     46386.750000   47298.750000    2014.000000       4.000000
50%     92773.500000   93685.500000    2016.000000       7.000000
75%    139160.250000  140072.250000    2019.000000      10.000000
max    185547.000000  186459.000000    2021.000000      12.000000

                 Day           Hour        Minute    Temperature  \
count  185548.000000  185548.000000  185548.00000  185548.000000
mean       15.736844      11.499245      15.00000      10.414422
std         8.799359       6.922132      15.00004      12.330547
min         1.000000       0.000000       0.00000     -35.400000
25%         8.000000       5.000000       0.00000       0.400000
50%        16.000000      11.000000      15.00000      11.100000
75%        23.000000      17.000000      30.00000      20.800000
max        31.000000      23.000000      30.00000      43.000000

        Clearsky DHI   Clearsky DNI   Clearsky GHI      Dew Point  \
count  185548.000000  185548.000000  185548.000000  185548.000000
mean       44.682875     345.789456     232.132952       5.863564
std        54.871686     380.670318     304.027444      11.624887
min         0.000000       0.000000       0.000000     -39.800000
25%         0.000000       0.000000       0.000000      -2.600000
50%         7.000000      32.000000       7.000000       6.300000
75%        85.000000     763.000000     454.000000      15.900000
max       496.000000    1062.000000    1028.000000      28.600000

                 DHI            DNI      Fill Flag            GHI  \
count  185548.000000  185548.000000  185548.000000  185548.000000
mean       62.171939     200.112990       3.131325     171.660918
std        93.782241     315.947293      14.489997     256.529740
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         4.000000       0.000000       0.000000       3.000000
75%        94.000000     348.000000       0.000000     284.000000
max       478.000000    1062.000000     100.000000    1028.000000

       Relative Humidity  Solar Zenith Angle  Surface Albedo       Pressure  \
count      185548.000000       185548.000000   185548.000000  185548.000000
mean           76.218206           89.626883        0.249904     990.592246
std            18.224555           35.317896        0.216762       7.152734
min            16.250000           18.280000        0.130000     958.000000
25%            64.090000           62.390000        0.150000     986.000000
50%            79.700000           89.270000        0.160000     990.000000
75%            91.230000          116.830000        0.170000     995.000000
max           100.000000          161.770000        0.800000    1020.000000

       Precipitable Water  Wind Direction     Wind Speed  \
count       185548.000000   185548.000000  185548.000000
mean             1.968824      196.227504       3.162491
std              1.315677       99.482750       1.771139
min              0.100000        0.000000       0.200000
25%              0.900000      124.000000       1.800000
50%              1.600000      195.000000       2.900000
75%              2.900000      287.000000       4.200000
max              6.900000      360.000000      13.800000

       Global Horizontal UV Irradiance (280-400nm)  \
count                                 185548.00000
mean                                       9.62328
std                                       15.25821
min                                        0.00000
25%                                        0.00000
50%                                        0.00000
75%                                       15.29745
max                                       63.07490

       Global Horizontal UV Irradiance (295-385nm)        Energy
count                                185548.000000  1.797440e+05
mean                                      7.536041  9.680209e+28
std                                      11.984242  2.852099e+29
min                                       0.000000  0.000000e+00
25%                                       0.000000  0.000000e+00
50%                                       0.000000  3.512961e+00
75%                                      11.906800  3.149476e+01
max                                      49.666500  7.020000e+30

In [28]:
df_final_ev = df_final_ev[df_final_ev['Energy']<=49.5]

In [29]:
df_final_ev

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy
0,0,912,2011,6,2,0,0,17.0,0,0,0,7,13.9,0,0,0,0,82.08,116.20,0.17,994,2.3,115,1.5,0.0000,0.0000,0.000000
1,1,913,2011,6,2,0,30,17.0,0,0,0,6,13.9,0,0,0,0,82.17,115.92,0.17,995,2.4,124,1.6,0.0000,0.0000,0.000000
2,2,914,2011,6,2,1,0,17.0,0,0,0,7,14.0,0,0,0,0,82.39,114.90,0.17,995,2.4,134,1.7,0.0000,0.0000,0.000000
3,3,915,2011,6,2,1,30,16.8,0,0,0,7,14.0,0,0,0,0,83.44,113.17,0.17,995,2.5,134,1.8,0.0000,0.0000,0.000000
4,4,916,2011,6,2,2,0,16.7,0,0,0,7,13.9,0,0,0,0,83.30,110.78,0.17,994,2.5,134,1.8,0.0000,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185543,185543,186455,2021,12,31,11,30,1.0,94,805,430,0,-0.6,94,777,0,419,89.34,65.31,0.74,976,1.2,81,3.9,22.2973,17.3511,11.996000
185544,185544,186456,2021,12,31,12,0,1.2,99,800,441,0,0.0,102,744,0,420,92.01,64.70,0.74,976,1.1,84,3.6,22.4516,17.4800,5.023000
185545,185545,186457,2021,12,31,12,30,1.3,101,792,438,8,0.0,122,342,4,267,91.35,64.84,0.74,976,1.1,83,3.3,14.2582,11.0996,4.866700
185546,185546,186458,2021,12,31,13,0,1.3,103,770,420,7,0.3,124,135,11,180,93.29,65.72,0.74,976,1.1,81,3.0,9.5491,7.4282,2.872722
185547,185547,186459,2021,12,31,13,30,1.3,100,749,389,7,0.3,89,27,29,99,93.29,67.30,0.74,976,1.1,72,2.7,5.1869,4.0289,3.399222

In [30]:
df_final_ev['conversion_efficiency'] = df_final_ev['Energy']*1000/(df_final_ev['GHI']*16.7225)

In [31]:
df_final_ev.head(30)

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency
0,0,912,2011,6,2,0,0,17.0,0,0,0,7,13.9,0,0,0,0,82.08,116.20,0.17,994,2.3,115,1.5,0.0000,0.0000,0.000000,NaN
1,1,913,2011,6,2,0,30,17.0,0,0,0,6,13.9,0,0,0,0,82.17,115.92,0.17,995,2.4,124,1.6,0.0000,0.0000,0.000000,NaN
2,2,914,2011,6,2,1,0,17.0,0,0,0,7,14.0,0,0,0,0,82.39,114.90,0.17,995,2.4,134,1.7,0.0000,0.0000,0.000000,NaN
3,3,915,2011,6,2,1,30,16.8,0,0,0,7,14.0,0,0,0,0,83.44,113.17,0.17,995,2.5,134,1.8,0.0000,0.0000,0.000000,NaN
4,4,916,2011,6,2,2,0,16.7,0,0,0,7,13.9,0,0,0,0,83.30,110.78,0.17,994,2.5,134,1.8,0.0000,0.0000,0.000000,NaN
5,5,917,2011,6,2,2,30,16.6,0,0,0,6,13.9,0,0,0,0,83.83,107.81,0.17,994,2.6,133,2.0,0.0000,0.0000,0.000000,NaN
6,6,918,2011,6,2,3,0,16.5,0,0,0,6,13.7,0,0,0,0,83.72,104.32,0.17,994,2.6,132,2.1,0.0000,0.0000,0.000000,NaN
7,7,919,2011,6,2,3,30,16.2,0,0,0,7,13.7,0,0,0,0,85.33,100.39,0.17,994,2.7,129,2.2,0.0000,0.0000,0.000000,NaN
8,8,920,2011,6,2,4,0,16.0,0,0,0,6,13.8,0,0,0,0,86.74,96.08,0.17,994,2.8,126,2.2,0.0000,0.0000,0.000000,NaN
9,9,921,2011,6,2,4,30,16.2,0,0,0,6,13.8,0,0,0,0,85.73,91.46,0.17,995,2.9,124,2.6,0.0000,0.0000,0.000000,NaN
10,10,922,2011,6,2,5,0,16.3,24,79,29,6,14.2,16,0,7,16,87.38,86.37,0.17,995,3.0,121,2.9,0.0000,0.0000,0.000000,0.000000
11,11,923,2011,6,2,5,30,16.5,57,228,91,6,14.2,35,0,7,35,86.28,81.38,0.17,995,3.1,115,3.2,0.0000,0.0000,0.000000,0.000000
12,12,924,2011,6,2,6,0,16.7,89,322,166,6,14.9,29,0,0,29,88.89,76.14,0.17,995,3.2,109,3.5,1.4047,1.0773,0.000000,0.000000
13,13,925,2011,6,2,6,30,17.1,113,421,252,6,14.9,5,0,0,5,86.67,70.76,0.17,995,3.3,103,3.8,0.2542,0.1967,0.006121,0.073209
14,14,926,2011,6,2,7,0,17.5,139,481,340,6,15.6,33,0,0,33,88.55,65.26,0.17,995,3.3,98,4.2,1.7568,1.3671,0.000000,0.000000
15,15,927,2011,6,2,7,30,18.1,156,543,430,6,15.6,29,0,0,29,85.19,59.70,0.17,994,3.4,99,4.4,1.6016,1.2511,0.357053,0.736264
16,16,928,2011,6,2,8,0,18.7,179,574,515,6,16.1,200,15,0,209,84.86,54.10,0.17,994,3.5,100,4.7,11.8756,9.3003,1.286750,0.368169
17,17,929,2011,6,2,8,30,19.4,191,615,598,6,16.1,233,19,0,246,81.25,48.51,0.17,994,3.6,107,4.9,14.2869,11.2081,3.062750,0.744518
18,18,930,2011,6,2,9,0,20.0,214,622,669,6,16.4,176,4,0,179,79.86,42.99,0.17,994,3.8,114,5.2,10.5715,8.3036,6.049500,2.020995
19,19,931,2011,6,2,9,30,20.6,224,648,737,7,16.4,58,0,0,58,76.97,37.59,0.17,994,3.9,121,5.4,3.4697,2.7278,12.596001,12.986840
20,20,932,2011,6,2,10,0,21.3,246,645,790,7,17.0,64,0,0,64,76.63,32.44,0.17,994,4.0,128,5.5,3.8659,3.0412,1.452632,1.357295
21,21,933,2011,6,2,10,30,21.6,252,659,836,6,17.0,249,13,0,260,75.24,27.69,0.17,994,4.2,134,5.4,15.8173,12.4484,4.496541,1.034199
22,22,934,2011,6,2,11,0,21.9,275,644,864,6,18.2,297,17,0,313,79.34,23.64,0.17,994,4.3,139,5.3,19.1350,15.0640,4.668304,0.891895
23,23,935,2011,6,2,11,30,22.1,277,650,885,6,18.1,216,11,0,226,78.30,20.72,0.17,993,4.4,144,5.2,13.8569,10.9107,2.696500,0.713495
24,24,936,2011,6,2,12,0,22.2,325,589,881,6,19.3,189,9,0,198,83.48,19.46,0.17,993,4.4,148,5.0,12.1538,9.5704,7.394000,2.233125
25,25,937,2011,6,2,12,30,22.4,324,588,876,6,19.3,219,11,0,229,82.47,20.18,0.17,993,4.4,152,5.0,14.0477,11.0613,1.631333,0.425996
26,26,938,2011,6,2,13,0,22.6,302,608,863,7,20.0,172,7,0,178,85.49,22.69,0.17,992,4.4,156,5.0,10.8928,8.5759,5.525000,1.856142
27,27,939,2011,6,2,13,30,22.8,297,598,832,7,20.0,213,10,0,222,84.46,26.47,0.17,992,4.4,158,4.8,13.5269,10.6469,3.019750,0.813424
28,28,940,2011,6,2,14,0,23.1,268,617,796,7,20.6,223,10,0,232,85.69,31.06,0.17,992,4.3,161,4.7,14.0452,11.0504,2.344187,0.604231
29,29,941,2011,6,2,14,30,23.2,259,597,741,7,20.6,333,39,0,364,85.17,36.12,0.17,992,4.3,163,4.5,21.8408,17.1738,6.739217,1.107151

In [32]:
(df_final_ev['Energy'].sum())*1000/(df_final_ev['GHI'].sum()*16.7225)

2.7513865280792937

In [33]:
df_final_ev[(df_final_ev['Month']==6)&(df_final_ev['Year']==2011)&(df_final_ev['Hour']==9)&(df_final_ev['Minute']==30)]

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency
19,19,931,2011,6,2,9,30,20.6,224,648,737,7,16.4,58,0,0,58,76.97,37.59,0.17,994,3.9,121,5.4,3.4697,2.7278,12.596001,12.986840
67,67,979,2011,6,3,9,30,29.1,159,755,757,0,23.7,159,755,0,757,72.80,37.54,0.17,989,3.8,185,5.5,45.2906,35.6060,25.723501,2.032043
115,115,1027,2011,6,4,9,30,26.6,252,594,723,4,22.6,357,69,0,412,78.64,37.49,0.17,993,4.0,156,1.5,24.6522,19.3809,25.134502,3.648143
163,163,1075,2011,6,5,9,30,26.5,212,661,737,3,19.1,322,404,0,643,64.00,37.45,0.17,993,3.7,114,3.2,38.4774,30.2500,8.315403,0.773341
211,211,1123,2011,6,6,9,30,29.5,136,806,776,0,23.3,136,806,0,776,69.48,37.42,0.17,986,3.1,209,4.4,46.4391,36.5094,24.511667,1.888904
259,259,1171,2011,6,7,9,30,29.2,163,762,768,0,23.4,163,762,0,768,71.04,37.39,0.17,985,2.8,209,4.2,45.9632,36.1355,24.797503,1.930837
307,307,1219,2011,6,8,9,30,28.4,371,388,679,7,23.7,359,307,0,603,75.81,37.36,0.17,983,3.9,219,4.7,36.0905,28.3739,5.731670,0.568411
355,355,1267,2011,6,9,9,30,22.8,273,561,718,6,17.0,144,1,0,145,69.92,37.34,0.17,990,4.0,57,2.6,8.6788,6.8232,2.177500,0.898026
403,403,1315,2011,6,10,9,30,22.5,205,700,762,3,18.8,223,10,0,231,79.67,37.33,0.18,987,2.7,231,1.1,13.8266,10.8703,12.956501,3.354089
451,451,1363,2011,6,11,9,30,21.1,108,885,812,3,14.9,186,6,0,191,67.83,37.32,0.18,989,1.8,322,3.8,11.4326,8.9882,7.480984,2.342201
499,499,1411,2011,6,12,9,30,19.8,192,727,770,7,13.2,301,450,0,659,65.72,37.31,0.18,993,2.5,87,3.2,39.4463,31.0124,15.112501,1.371354
547,547,1459,2011,6,13,9,30,20.4,126,833,789,0,10.6,126,833,0,789,53.27,37.31,0.18,993,2.7,101,4.8,47.2279,37.1302,27.022001,2.048044
595,595,1507,2011,6,14,9,30,21.6,226,643,738,7,17.2,381,155,0,504,75.93,37.31,0.18,987,3.9,130,5.9,30.1684,23.7181,8.445500,1.002060
643,643,1555,2011,6,15,9,30,22.7,125,826,782,7,19.4,276,19,0,291,81.58,37.32,0.17,979,3.0,284,5.0,17.4183,13.6941,1.204013,0.247421
691,691,1603,2011,6,16,9,30,25.1,113,862,799,7,15.6,241,617,0,732,55.74,37.34,0.17,984,2.2,285,3.6,43.8132,34.4455,27.254002,2.226476
739,739,1651,2011,6,17,9,30,25.2,185,708,748,6,22.2,228,11,0,237,83.61,37.36,0.17,983,4.0,131,2.8,14.1848,11.1519,24.367500,6.148390
787,787,1699,2011,6,18,9,30,24.6,151,763,757,7,21.7,365,276,0,585,83.96,37.38,0.17,984,4.3,121,2.9,35.0117,27.5257,13.079500,1.337008
835,835,1747,2011,6,19,9,30,25.1,170,733,753,7,22.5,363,286,0,590,85.30,37.41,0.17,981,4.0,114,1.3,35.3088,27.7591,20.672707,2.095290
883,883,1795,2011,6,20,9,30,23.6,243,604,722,6,22.2,365,82,0,431,91.81,37.44,0.17,978,4.2,161,3.3,25.7917,20.2769,6.174500,0.856689
931,931,1843,2011,6,21,9,30,26.5,175,722,748,4,22.4,379,128,0,481,78.22,37.48,0.16,975,3.7,176,7.0,28.7814,22.6272,23.986919,2.982141
979,979,1891,2011,6,22,9,30,20.4,115,830,773,4,16.5,134,0,0,134,78.26,37.52,0.16,976,3.6,242,6.0,8.0174,6.3031,7.811501,3.486009
1027,1027,1939,2011,6,23,9,30,20.2,93,876,787,0,14.2,93,876,0,787,68.56,37.56,0.16,980,3.1,288,5.7,47.0835,37.0154,14.580501,1.107890
1075,1075,1987,2011,6,24,9,30,20.6,112,873,803,0,14.0,112,873,0,803,65.89,37.61,0.16,986,1.8,333,4.0,48.0357,37.7637,17.107109,1.273972
1123,1123,2035,2011,6,25,9,30,22.8,142,785,764,9,16.1,94,0,0,94,66.09,37.66,0.16,988,3.5,132,3.5,5.6225,4.4202,5.851500,3.722530
1171,1171,2083,2011,6,26,9,30,24.4,125,821,775,3,19.1,273,528,0,691,72.17,37.72,0.16,988,3.0,122,4.2,41.3262,32.4885,27.420900,2.373026
1219,1219,2131,2011,6,27,9,30,26.5,135,788,758,6,23.5,370,101,0,450,83.67,37.78,0.16,983,4.1,257,5.6,26.9094,21.1546,14.897501,1.979701
1267,1267,2179,2011,6,28,9,30,22.9,85,924,816,0,14.3,85,924,0,816,58.56,37.84,0.16,994,1.5,337,2.1,48.7896,38.3551,26.718000,1.958000
1315,1315,2227,2011,6,29,9,30,24.7,103,871,790,0,16.5,103,871,0,790,60.29,37.91,0.16,994,2.4,172,3.1,47.2280,37.1271,25.568308,1.935413
1363,1363,2275,2011,6,30,9,30,28.5,118,814,760,0,24.3,118,814,0,760,77.96,37.99,0.16,988,4.2,177,4.4,45.4267,35.7107,24.196001,1.903833

In [34]:
df_final_ev_cons = df_final_ev[df_final_ev['conversion_efficiency']<=0.148]

In [35]:
df_final_ev_cons['conversion_efficiency'].describe()

count    10074.000000
mean         0.029424
std          0.043638
min          0.000000
25%          0.000000
50%          0.000000
75%          0.051826
max          0.147984
Name: conversion_efficiency, dtype: float64

In [36]:
df_final_ev_cons

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency
10,10,922,2011,6,2,5,0,16.3,24,79,29,6,14.2,16,0,7,16,87.38,86.37,0.17,995,3.0,121,2.9,0.0000,0.0000,0.000000,0.000000
11,11,923,2011,6,2,5,30,16.5,57,228,91,6,14.2,35,0,7,35,86.28,81.38,0.17,995,3.1,115,3.2,0.0000,0.0000,0.000000,0.000000
12,12,924,2011,6,2,6,0,16.7,89,322,166,6,14.9,29,0,0,29,88.89,76.14,0.17,995,3.2,109,3.5,1.4047,1.0773,0.000000,0.000000
13,13,925,2011,6,2,6,30,17.1,113,421,252,6,14.9,5,0,0,5,86.67,70.76,0.17,995,3.3,103,3.8,0.2542,0.1967,0.006121,0.073209
14,14,926,2011,6,2,7,0,17.5,139,481,340,6,15.6,33,0,0,33,88.55,65.26,0.17,995,3.3,98,4.2,1.7568,1.3671,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185503,185503,186415,2021,12,30,15,30,-1.4,56,548,155,0,-2.6,56,419,7,131,91.42,79.63,0.80,982,0.8,216,1.7,6.2439,4.7602,0.062611,0.028581
185504,185504,186416,2021,12,30,16,0,-2.4,40,399,83,4,-3.6,37,150,71,53,91.48,83.79,0.80,982,0.8,213,1.3,0.0000,0.0000,0.061111,0.068951
185505,185505,186417,2021,12,30,16,30,-3.1,17,151,22,4,-3.6,9,0,86,9,96.35,88.14,0.80,982,0.7,210,1.3,0.0000,0.0000,0.019500,0.129566
185537,185537,186449,2021,12,31,8,30,-2.4,44,497,112,0,-3.9,44,497,0,112,89.63,82.09,0.74,979,1.0,87,4.3,0.0000,0.0000,0.000000,0.000000
185538,185538,186450,2021,12,31,9,0,-1.7,57,615,184,4,-2.8,69,154,0,101,92.48,78.06,0.74,979,1.1,82,4.4,4.8321,3.6928,0.000000,0.000000

In [37]:
df_final_ev_cons.to_csv('EV.csv')

In [38]:
(df_final_ev_cons['Energy'].sum())*1000*100/(df_final_ev_cons['GHI'].sum()*16.7225)

5.044444032911707

In [37]:
df_final_ev_cons.dtypes

level_0                                          int64
index                                            int64
Year                                             int64
Month                                            int64
Day                                              int64
Hour                                             int64
Minute                                           int64
Temperature                                    float64
Clearsky DHI                                     int64
Clearsky DNI                                     int64
Clearsky GHI                                     int64
Cloud Type                                      object
Dew Point                                      float64
DHI                                              int64
DNI                                              int64
Fill Flag                                        int64
GHI                                              int64
Relative Humidity                              float64
Solar Zenith Angle                             float64
Surface Albedo                                 float64
Pressure                                         int64
Precipitable Water                             float64
Wind Direction                                   int64
Wind Speed                                     float64
Global Horizontal UV Irradiance (280-400nm)    float64
Global Horizontal UV Irradiance (295-385nm)    float64
Energy                                         float64
conversion_efficiency                          float64
dtype: object

In [38]:
result_year = df_final_ev_cons.groupby('Year')['Energy'].sum()*1000*100/(df_final_ev_cons.groupby('Year')['GHI'].sum()*16.7225)

print(result_year)

Year
2011    3.633789
2012    3.382694
2013    3.615624
2014    5.797614
2015    5.896117
2016    6.577797
2017    3.249060
2018    4.244359
2019    4.173419
2020    5.087985
2021    4.919366
dtype: float64

In [39]:
result_month = df_final_ev_cons.groupby('Month')['Energy'].sum()*1000*100/(df_final_ev_cons.groupby('Month')['GHI'].sum()*16.7225)

print(result_month)

Month
1     4.088586
2     5.373906
3     3.249801
4     4.991310
5     4.660064
6     5.469911
7     4.035486
8     4.646413
9     4.549135
10    4.036447
11    3.636494
12    3.817945
dtype: float64

In [42]:
query = ''' WITH CTE as (SELECT * FROM df_final_ev_cons)
SELECT *, sum(GHI) over(partition by Minute) as Hourly_GHI, 
sum(Energy) over(partition by Minute) as Hourly_Energy FROM CTE GROUP by Year, Month, Day, Hour, Minute, Temperature, "Clearsky DHI",
       "Clearsky DNI", "Clearsky GHI", "Cloud Type", "Dew Point", DHI, DNI,
       "Fill Flag", GHI, "Relative Humidity", "Solar Zenith Angle",
       "Surface Albedo", Pressure, "Precipitable Water", "Wind Direction",
       "Wind Speed", "Global Horizontal UV Irradiance (280-400nm)",
       "Global Horizontal UV Irradiance (295-385nm)"
'''

In [43]:
EV_hourly = sqldf(query)

In [45]:
EV_hourly.head()

,level_0,index,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,DHI,DNI,Fill Flag,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Precipitable Water,Wind Direction,Wind Speed,Global Horizontal UV Irradiance (280-400nm),Global Horizontal UV Irradiance (295-385nm),Energy,conversion_efficiency,Hourly_GHI,Hourly_Energy
0,10,922,2011,6,2,5,0,16.3,24,79,29,6,14.2,16,0,7,16,87.38,86.37,0.17,995,3.0,121,2.9,0.0000,0.0000,0.0,0.0,735852,626.248371
1,12,924,2011,6,2,6,0,16.7,89,322,166,6,14.9,29,0,0,29,88.89,76.14,0.17,995,3.2,109,3.5,1.4047,1.0773,0.0,0.0,735852,626.248371
2,14,926,2011,6,2,7,0,17.5,139,481,340,6,15.6,33,0,0,33,88.55,65.26,0.17,995,3.3,98,4.2,1.7568,1.3671,0.0,0.0,735852,626.248371
3,58,970,2011,6,3,5,0,19.7,22,79,27,7,19.4,22,30,7,24,98.29,86.32,0.17,990,3.6,171,3.7,0.0000,0.0000,0.0,0.0,735852,626.248371
4,106,1018,2011,6,4,5,0,22.3,21,58,24,7,22.2,22,25,7,24,99.15,86.27,0.17,991,4.3,250,2.6,0.0000,0.0000,0.0,0.0,735852,626.248371

In [46]:
EV_hourly['conversion_efficiency'] = EV_hourly['Hourly_Energy']*1000/(EV_hourly['Hourly_GHI']*16.7225)

In [48]:
sorted_EV_hourly = EV_hourly.sort_values(by = 'Hour')

In [49]:
selected_columns_df = sorted_EV_hourly[['Year','Month', 'Day','Hour','GHI','Energy','conversion_efficiency']]

# Specify the path where you want to save the CSV file

# Write the selected columns to the CSV file
selected_columns_df.to_csv('EV_Hourly_eff.csv')

In [50]:
query_Daily = ''' WITH CTE as (SELECT * FROM df_final_ev_cons)
SELECT *, sum(GHI) over(partition by Hour) as Daily_GHI, 
sum(Energy) over(partition by Hour) as Daily_Energy FROM CTE GROUP by Year, Month, Day, Hour, Minute, Temperature, "Clearsky DHI",
       "Clearsky DNI", "Clearsky GHI", "Cloud Type", "Dew Point", DHI, DNI,
       "Fill Flag", GHI, "Relative Humidity", "Solar Zenith Angle",
       "Surface Albedo", Pressure, "Precipitable Water", "Wind Direction",
       "Wind Speed", "Global Horizontal UV Irradiance (280-400nm)",
       "Global Horizontal UV Irradiance (295-385nm)"
'''

In [52]:
EV_Daily_df = sqldf(query_Daily)

In [53]:
EV_Daily_df['conversion_efficiency'] = EV_Daily_df['Daily_Energy']*1000/(EV_Daily_df['Daily_GHI']*16.7225)

In [54]:
EV_sorted_daily_df= EV_Daily_df.sort_values(by = 'Day')

In [55]:

# Create a new DataFrame with only the selected columns
selected_columns_df = EV_sorted_daily_df[['Year','Month', 'Day','GHI','Energy','conversion_efficiency']]

# Specify the path where you want to save the CSV file

# Write the selected columns to the CSV file
selected_columns_df.to_csv('EV_Daily_eff.csv')